name: hummingbird
description: Placeholder for future work
version: 0.0.1
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/hummingbird

environment:
  sdk: '>=2.1.0 <3.0.0'
